services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./lib/db/migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
